[package]
name = "bark-device"
version = "0.0.0"
edition = "2021"

[dependencies]
bark-protocol = { workspace = true }
cpal = { workspace = true }
derive_more = { workspace = true }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
