[package]
name = "bark-util"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bark-protocol = { workspace = true }
nix = { workspace = true }
libc = "0.2"
